### ISSUE TITLE
[Bug]: 登录账户时崩溃

### ISSUE THREAD

**Issue by ArthurZhou** [zly2006/reden-is-what-we-made#103]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

登录github账户时出错

### Reproduction

打开登录页面并选择Login to Github

### Relevant log output (if applicable)

```Shell
---- Minecraft Crash Report ----
// My bad.

Time: 2024-03-22 23:30:14
Description: mouseClicked event handler

kotlin.NotImplementedError: An operation is not implemented.
	at com.github.zly2006.reden.rvc.remote.github.GithubAuthKt.<clinit>(GithubAuth.kt:15)
	at com.github.zly2006.reden.rvc.remote.github.GithubAuth.genCode(GithubAuth.kt:46)
	at com.github.zly2006.reden.rvc.remote.github.GithubAuthScreen.login2GithubButton$lambda$2(GithubAuthScreen.kt:51)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:95)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:48)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:145)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:99)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:414)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:99)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:180)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at net.minecraft.client.util.Window.swapBuffers(Window.java:287)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1349)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.zly2006.reden.rvc.remote.github.GithubAuthKt.<clinit>(GithubAuth.kt:15)
	at com.github.zly2006.reden.rvc.remote.github.GithubAuth.genCode(GithubAuth.kt:46)
	at com.github.zly2006.reden.rvc.remote.github.GithubAuthScreen.login2GithubButton$lambda$2(GithubAuthScreen.kt:51)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:95)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:48)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:145)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:99)

-- Affected screen --
Details:
	Screen name: com.github.zly2006.reden.rvc.remote.github.GithubAuthScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:414)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:99)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:180)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213)
	at net.minecraft.client.util.Window.swapBuffers(Window.java:287)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1349)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 944348752 bytes (900 MiB) / 2726297600 bytes (2600 MiB) up to 12859736064 bytes (12264 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 56203.70
	Virtual memory used (MB): 19414.36
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	Fabric Mods: 
		carpet: Carpet Mod 1.4.128+v231205
		exo: Exo 0.1.5+1.19
		fabric-api: Fabric API 0.96.3+1.20.4
		fabric-api-base: Fabric API Base 0.4.36+78d798af4f
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
		fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
		fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
		fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
		fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
		fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
		fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.13+78d798af4f
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
		fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.2+b90db5744f
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.2+5c0133444f
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.3.3+85d85a934f
		fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.24+f9b333cc4f
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
		fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
		fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.63+78d798af4f
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
		fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
		fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.12+080016e44f
		fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
		fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
		fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
		fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+e84342304f
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabricloader: Fabric Loader 0.15.7
		ferritecore: FerriteCore 6.0.3
		ias: In-Game Account Switcher 8.0.2
		isometric-renders: Isometric Renders 0.4.7+1.20.3
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.17.1
		malilib: MaLiLib 0.18.1
		minecraft: Minecraft 1.20.4
		mixinextras: MixinExtras 0.3.1
		modmenu: Mod Menu 9.0.0
		notenoughcrashes: Not Enough Crashes 4.4.7+1.20.4
		owo: oÏ‰o 0.12.5+1.20.3
		reden: Reden is What We Make 0.2.596+fba66d4-dev
		tweakeroo: Tweakeroo 0.19.2
		worldmesher: Worldmesher 0.4.5+1.20.3
	Reden Debugger: Disabled
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Reden is What We Make (reden)
```

### Environment

- **win10 enterprise ltsc**:
- **1.20.4**:
- **fba66d40**:

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists
- [X] I enabled `redenDebug` in carpet or `debugLogger` options in malilib screen for my log

**Comment by zly2006** [comment]
此处的登录界面属于开发中状态，不应该使用，如果您需要push提交，可以直接在rvc节目点击push并登录reden账号。

你也可以用外部git手动提交

**Comment by ArthurZhou** [comment]
还有一个问题，登录reden时会抛出如下错误

![image](https://github.com/zly2006/reden-is-what-we-made/assets/89689293/fa878fa8-65d1-4a47-bb1d-c72a7e8f81ba)

这属于正常行为，不应当显示为错误

**Comment by zly2006** [comment]
> 还有一个问题，登录reden时会抛出如下错误
> 
> ![image](https://private-user-images.githubusercontent.com/89689293/316083429-fa878fa8-65d1-4a47-bb1d-c72a7e8f81ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI3MjUsIm5iZiI6MTcxMTEyMjQyNSwicGF0aCI6Ii84OTY4OTI5My8zMTYwODM0MjktZmE4NzhmYTgtNjVkMS00YTQ3LWJiMWQtYzcyYTdlOGY4MWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE1NDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NWNiZTVkYzU2NWM1ZGMwNDllNWE3OWY4MTJhNzg5YTMzY2UxZmU2YjNiYjU4NDlmM2M5YzdlODI5ZGVmYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KHj3LIrxJ0rVCgVtWI6GkxNACizVuwzPtwzQzZYFxBU)
> 
> 这属于正常行为，不应当显示为错误

# **还在开发中**
