### ISSUE TITLE
[Bug/Outdated]: Multiple threads access

### ISSUE THREAD

**Issue by vocaloidkiss** [zly2006/reden-is-what-we-made#17]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

当我使用tick warp 72000时，游戏在短时间内进行72000tick的运算，reden导致游戏崩溃，同时还可能伴有锂模组崩溃

### 重现

安装地毯和reden
建造一个活塞，漏斗和堆肥桶较多的红石结构，运行tick warp 72000

### 环境

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-08-30 17:46:56
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper$monitorSetBlock$1.invoke(UpdateMonitorHelper.kt:79)
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper$monitorSetBlock$1.invoke(UpdateMonitorHelper.kt:78)
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper.monitorSetBlock$lambda$3(UpdateMonitorHelper.kt:78)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper.monitorSetBlock(UpdateMonitorHelper.kt:78)
	at net.minecraft.class_2818.handler$gml000$reden$monitorSetBlock(class_2818.java:5712)
	at net.minecraft.class_2818.method_12010(class_2818.java)
	at net.minecraft.class_1937.method_30092(class_1937.java:228)
	at net.minecraft.class_1937.method_8652(class_1937.java:213)
	at net.minecraft.class_3962.method_17756(class_3962.java:297)
	at net.minecraft.class_3962$class_3963.method_5431(class_3962.java:450)
	at net.minecraft.class_1277.redirect$egj000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:1543)
	at net.minecraft.class_1277.method_5447(class_1277.java:144)
	at me.jellysquid.mods.lithium.common.hopper.HopperHelper.tryMoveSingleItem(HopperHelper.java:91)
	at me.jellysquid.mods.lithium.common.hopper.HopperHelper.tryMoveSingleItem(HopperHelper.java:69)
	at net.minecraft.class_2614.handler$fme000$lithium$lithiumInsert(class_2614.java:693)
	at net.minecraft.class_2614.method_11246(class_2614.java:148)
	at net.minecraft.class_2614.method_11243(class_2614.java:115)
	at net.minecraft.class_2614.method_31692(class_2614.java:102)
	at net.minecraft.class_2818$class_5563.redirect$zmi000$carpet$checkProcessBEs(class_2818.java:790)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18765$295(MinecraftServer.java)
	at net.minecraft.server.MinecraftServer.wrapOperation$clp000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:6840)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$zmf000$carpet$modifiedRunLoop(MinecraftServer.java:16942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper$monitorSetBlock$1.invoke(UpdateMonitorHelper.kt:79)
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper$monitorSetBlock$1.invoke(UpdateMonitorHelper.kt:78)
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper.monitorSetBlock$lambda$3(UpdateMonitorHelper.kt:78)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at com.github.zly2006.reden.mixinhelper.UpdateMonitorHelper.monitorSetBlock(UpdateMonitorHelper.kt:78)
	at net.minecraft.class_2818.handler$gml000$reden$monitorSetBlock(class_2818.java:5712)
	at net.minecraft.class_2818.method_12010(class_2818.java)
	at net.minecraft.class_1937.method_30092(class_1937.java:228)
	at net.minecraft.class_1937.method_8652(class_1937.java:213)
	at net.minecraft.class_3962.method_17756(class_3962.java:297)
	at net.minecraft.class_3962$class_3963.method_5431(class_3962.java:450)
	at net.minecraft.class_1277.redirect$egj000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:1543)
	at net.minecraft.class_1277.method_5447(class_1277.java:144)
	at me.jellysquid.mods.lithium.common.hopper.HopperHelper.tryMoveSingleItem(HopperHelper.java:91)
	at me.jellysquid.mods.lithium.common.hopper.HopperHelper.tryMoveSingleItem(HopperHelper.java:69)
	at net.minecraft.class_2614.handler$fme000$lithium$lithiumInsert(class_2614.java:693)
	at net.minecraft.class_2614.method_11246(class_2614.java:148)
	at net.minecraft.class_2614.method_11243(class_2614.java:115)
	at net.minecraft.class_2614.method_31692(class_2614.java:102)
	at net.minecraft.class_2818$class_5563.redirect$zmi000$carpet$checkProcessBEs(class_2818.java:790)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18765$295(MinecraftServer.java)
	at net.minecraft.server.MinecraftServer.wrapOperation$clp000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:6840)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (31,-41,40), Section: (at 15,7,8 in 1,-3,2; chunk contains blocks 16,-64,32 to 31,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (31,-41,40), Section: (at 15,7,8 in 1,-3,2; chunk contains blocks 16,-64,32 to 31,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18765$295(MinecraftServer.java)
	at net.minecraft.server.MinecraftServer.wrapOperation$clp000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:6840)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$zmf000$carpet$modifiedRunLoop(MinecraftServer.java:16942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['vocaloidkiss'/1, l='ServerLevel[交错阶梯式苔藓骨粉机]', x=26.75, y=-34.44, z=45.94]]
	Chunk stats: 3025
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 84580 game time, 2000 day time
	Level name: 交错阶梯式苔藓骨粉机
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.handler$zmf000$carpet$modifiedRunLoop(MinecraftServer.java:16942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 4464659128 bytes (4257 MiB) / 5570035712 bytes (5312 MiB) up to 20937965568 bytes (19968 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: Intel(R) UHD Graphics 770
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0xa780
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4338
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 69372.98
	Virtual memory used (MB): 14713.61
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 3.52
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx19968m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		armorchroma: Armor Chroma 1.2.6
		autofish: Simple Autofish 1.3.0
		badpackets: Bad Packets 0.4.1
		bedrockminer: Bedrock Miner 1.20.1-1.2.0
		betterbeds: Better Beds 1.3.0
		betterf3: BetterF3 7.0.1
		bettermounthud: Better Mount HUD 1.2.2
		betterpingdisplay: Better Ping Display 1.1.1
		boatiview: Boat Item View Fabric 0.0.5
		bsvsb: Better Sodium Video Settings Button 3.0.3
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.97
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.97
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.97
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.97
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.97
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.97
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.97
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.97
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.97
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.97
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.97
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.97
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.97
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.97
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.97
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.97
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.97
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.97
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.97
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.97
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.97
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		carpet: Carpet Mod 1.4.112+v230608
		carpet-ams-addition: Carpet AMS Addition 2.4.0+build.268
			org_yaml_snakeyaml: snakeyaml 2.0
		carpet-extra: Carpet Extra 1.4.115
		carpet-sls-addition: Carpet SLS Addition 0.6.1
		carpet-tis-addition: Carpet TIS Addition 1.50.1
		chat_heads: Chat Heads 0.10.20
		chatpatches: Chat Patches 201.5.5
		chesttracker: Chest Tracker 1.1.22
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
			whereisit: Where Is It 1.14.17
		chunksending: Chunksending Mod 1.20.1-2.5
		clientcommands: Client Commands 2.8.3
			betterconfig: BetterConfig 1.1.4
			clientarguments: clientarguments 1.5
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		cloudmusic: CloudMusic 0.4.5
			com_google_zxing_core: core 3.5.1
			com_googlecode_soundlibs_mp3spi: mp3spi 1.9.5.4
			com_googlecode_soundlibs_tritonus-share: tritonus-share 0.3.7.4
			javazoom_jlayer: jlayer 1.0.1
			org_jflac_jflac-codec: jflac-codec 1.5.2
		colormeoutlines: Color Me Outlines 1.1.2
		come-back-my-noteblock-supression: come-back-my-noteblock-supression 0.1
		continuity: Continuity 3.0.0-beta.3+1.20.1
		controlling: Controlling For Fabric 12.0.2
		customskinloader: CustomSkinLoader 14.17
		debugify: Debugify 1.20.1+2.0
		disc_jockey: Disc Jockey 1.2.5
		easiervillagertrading: EasierVillagerTrading 1.20-fabric0.83.0-1.5.4
			gbfabrictools: GBfabrictools 1.3.5+1.20
		enclosure: Enclosure 0.3.2+1.20
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		essential_commands: Essential Commands 0.33.2-mc1.20
			ec-core: Essential Commands Core 1.3.0-mc1.20
			placeholder-api: Placeholder API 2.1.1+1.20
			playerabilitylib: Pal 1.8.0
		exordium: Exordium 1.1.4-mc1.20.1
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.0+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.22
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 6.0.0
		gammautils: Gamma Utils 1.7.16
		gca: GugleCarpetAddition 2.7.0-1.20.1
		held-item-info: Held Item Info 1.5.0
		i18nupdatemod: I18nUpdateMod 3.5.0
		ias: In-Game Account Switcher 8.0.2
		imblocker: IMBlocker 4.0.5
		immediatelyfast: ImmediatelyFast 1.2.1+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.10
			net_lenni0451_reflect: Reflect 1.2.1
		indium: Indium 1.0.25+mc1.20.1
		inventoryhud: Inventory HUD + 3.4.15
		inventoryprofilesnext: Inventory Profiles Next 1.10.7
		invview: InvView 1.4.11-1.20+
			sgui: sgui 1.2.2+1.20
		iris: Iris 1.6.8
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemscroller: Item Scroller 0.20.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.5.8+1.20.1
		lanserverproperties: Lan Server Properties 1.11
		letmeclickandsend: Let Me Click And Send 1.1.0
		libipn: libIPN 4.0.0
		litematica: Litematica 0.15.3
		lithium: Lithium 0.11.2
		magiclib: MagicLib 0.7.350+8950a23-beta
			magiclib-1_20_1: MagicLib for 1.20.1 0.7.350+8950a23-beta
		malilib: MaLiLib 0.16.1
		masa_gadget_mod: Masa Gadget 3.2.313+03fb41f-beta
			masa_gadget_mod-1_20_1: Masa Gadget for 1.20.1 3.2.313+03fb41f-beta
		mcwifipnp: LAN World Plug-n-Play 1.6.5
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		modmenu: Mod Menu 7.2.1
		moreculling: More Culling 1.20.1-0.19.0
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		notenoughanimations: NotEnoughAnimations 1.6.4
		ommc-1_20_1: Oh My Minecraft Client for 1.20.1 0.5.294+e12a73f-beta
		paperdoll: PaperDoll 1.1.1-mc1.20
		pistorder: Pistorder 1.5.0
		quickshulker: Quick Shulker 1.4.0-1.20
			kyrptconfig: Kyrpt Config 1.5.4-1.20
			shulkerutils: shulkerutils 1.0.4-1.19
		recursiveresources: Recursive Resources 2.5.2+1.20
			cicada: CICADA 0.4.0
			shared-resources-api: Shared Resources API 1.5.2
		reden: Reden is What We Make 0.1+08241821
			com_squareup_okhttp3_okhttp: okhttp 4.11.0
			org_bouncycastle_bcpg-jdk18on: bcpg-jdk18on 1.76
			org_bouncycastle_bcprov-jdk18on: bcprov-jdk18on 1.76
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.1-build.95
		replaymod: Replay Mod 1.20.1-2.6.13
		roughlyenoughitems: Roughly Enough Items 12.0.645
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.1
		seedcrackerx: SeedCrackerX 2.14.4
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome 1.171.1
			com_seedfinding_mc_core: mc_core 1.194.0
			com_seedfinding_mc_feature: mc_feature 1.171.5
			com_seedfinding_mc_math: mc_math 1.171.0
			com_seedfinding_mc_noise: mc_noise 1.171.1
			com_seedfinding_mc_reversal: mc_reversal 1.171.1
			com_seedfinding_mc_seed: mc_seed 1.171.2
			com_seedfinding_mc_terrain: mc_terrain 1.171.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		sodium: Sodium 0.5.2
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sspb: Sodium Shadowy Path Blocks 3.2.0
		syncmatica: Syncmatica 1.20.1-0.3.10
		tiefix: TieFix 1.14.0
		trade_cycling: Trade Cycling 1.20.1-1.0.7
		tweakermore: TweakerMore 3.14.0
			conditional-mixin: conditional mixin 0.3.2
		tweakeroo: Tweakeroo 0.17.1
		tweakmyclient: Tweak My Client 3.6.401+38c9a34-stable
			tweakmyclient-1_20_1: Tweak My Client for 1.20.1 3.6.401+38c9a34-stable
		vanilla-permissions: Vanilla Permissions 0.2.2+1.20.1
		viafabricplus: ViaFabricPlus 2.8.2
		vmp: Very Many Players 0.2.0+beta.7.101
		voicechat: Simple Voice Chat 1.20.1-2.4.24
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		worldeditcui: WorldEditCUI 1.20+01
		wthit: wthit 8.4.0
		xaero_map_addition-1_20_1: Xaero Map Addition for 1.20.1 0.2.79+91bd337-beta
		xaerominimap: Xaero's Minimap 23.6.3
		xaeroworldmap: Xaero's World Map 1.33.0
		xaerozoomout: XaeroZoomout 1.0.0+mc1.20
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['vocaloidkiss'/1, l='ServerLevel[交错阶梯式苔藓骨粉机]', x=26.75, y=-34.44, z=45.94]]
	Data Packs: vanilla, fabric, file/AmsData (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1-Fabric 0.14.22

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by zly2006** [comment]
本 bug 在最新版本中仍存在

Please confirm this bug in the newest version.
