### ISSUE TITLE
服务端无法加载本模组

### ISSUE THREAD

**Issue by Grayer0113** [zly2006/reden-is-what-we-made#4]
**环境：**

- Minecraft 1.20.1
- Fabric Loader 0.14.22
- Java 17

**加载模组列表：**

- fabric-api-0.87.0+1.20.1.jar
- fabric-carpet-1.20-1.4.112+v230608.jar
- fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar
- malilib-fabric-1.20.1-0.16.1.jar
- reden-is-what-we-made-0.1+08201226.jar

**补充说明：**
`Malilib`本身无法在服务端加载，这里修改了`Malilib`的`fabric.mod.json`文件中`environment`配置项，使其可以在服务端加载

**报错：**
```log
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'reden'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
	at fi.dy.masa.malilib.config.options.ConfigBooleanHotkeyed.<init>(ConfigBooleanHotkeyed.java:20) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at com.github.zly2006.reden.malilib.MalilibSettingsKt.<clinit>(MalilibSettings.kt:38) ~[reden-is-what-we-made-0.1+08201226.jar:?]
	at com.github.zly2006.reden.pearl.PearlTask$Companion.register(PearlTask.kt:45) ~[reden-is-what-we-made-0.1+08201226.jar:?]
	at com.github.zly2006.reden.Reden.onInitialize(Reden.java:60) ~[reden-is-what-we-made-0.1+08201226.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at fi.dy.masa.malilib.config.options.ConfigBooleanHotkeyed.<init>(ConfigBooleanHotkeyed.java:20) ~[malilib-fabric-1.20.1-0.16.1.jar:?]
	at com.github.zly2006.reden.malilib.MalilibSettingsKt.<clinit>(MalilibSettings.kt:38) ~[reden-is-what-we-made-0.1+08201226.jar:?]
	at com.github.zly2006.reden.pearl.PearlTask$Companion.register(PearlTask.kt:45) ~[reden-is-what-we-made-0.1+08201226.jar:?]
	at com.github.zly2006.reden.Reden.onInitialize(Reden.java:60) ~[reden-is-what-we-made-0.1+08201226.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	... 8 more
```

**Comment by zly2006** [comment]
请检查最新版
